server:
  port: 8081
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12342234
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.example.demo.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:mapper/*.xml

  logging:
    level:
      com:
        example:
          demo:
            mapper: debug